### ISSUE TITLE
Reconcile settings.py and evolver.yml

### ISSUE THREAD

**Issue by imaitland** [ssec-jhu/evolver-ng#254]
It's not clear how the env vars in `settings.py` relate to similar settings in the `evolver.yml` config.

for example settings.py has variables:
```
ROOT_CALIBRATOR_FILE_STORAGE_PATH: Path = Path("calibration_files")
EXPERIMENT_FILE_STORAGE_PATH: Path = Path("experiment_files")
```

while the evolver.yml may have attributes in config like `dir` and `calibration_file`:

```
  temp:
    classinfo: evolver.hardware.standard.temperature.Temperature
    config:
      addr: temp
      calibrator:
        classinfo: evolver.calibration.standard.calibrators.temperature.TemperatureCalibrator
        config:
          calibration_file: foobar2000.yml
          created: '2024-11-20T21:06:13.563442'
          dir: calibration_files
```

If there's a coherent relationship between the two sources of truth it must be expressed in documentation. If it already exists, or is obvious, this issue can be closed with reference to the answer.
