### ISSUE TITLE
vials do not get list from evolver by default

### ISSUE THREAD

**Issue by amitschang** [ssec-jhu/evolver-ng#90]
When testing on the evolver box, I started with this config:

```yaml
vials:
- 0
- 5
- 10
- 15
hardware:
  od:
    classinfo: evolver.hardware.standard.od_sensor.ODSensor
    config:
      addr: od_90
  temp:
    classinfo: evolver.hardware.standard.temperature.Temperature
    config:
      addr: temp
```

and was expecting (hoping, maybe) that the vials list for sensors would be that of top-level evolver, however inspected state revealed all 16 vials. This could be corrected by specifying the `vials` in the `config` section of each hardware (as below), but this seems confusing and redundant.

Marking this as a bug since I think the desired behavior with the above config is to carry over the top-level vials by default.

----

Appendix:

This config produces desired result:

```yaml
vials:
- 0
- 5
- 10
- 15
hardware:
  od:
    classinfo: evolver.hardware.standard.od_sensor.ODSensor
    config:
      addr: od_90
      vials: [0, 5, 10, 15]
  temp:
    classinfo: evolver.hardware.standard.temperature.Temperature
    config:
      addr: temp
      vials: [0, 5, 10, 15]
```
